### ISSUE TITLE
Exception thrown (socket.cpp)

### ISSUE THREAD

**Issue by revson1** [embeddedmz/socket-cpp#14]
When im trying to compile my program i get
`Exception thrown at 0x0F8B3A44 (msvcp140d.dll) in networktest.exe: 0xC0000005: Access violation reading location 0x00000000.`

in line 31
`if (s_iSocketCount == 0)`

and in line 36
`WSAStartup(MAKEWORD(2, 2),&s_wsaData);`

also in output i get
`'networktest.exe' (Win32): Loaded 'C:\Users\krzys\source\repos\networktest\Debug\networktest.exe'. Symbols loaded.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140d.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
'networktest.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\ucrtbased.dll'
'networktest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. Cannot find or open the PDB file.
Exception thrown at 0x0F8B3A44 (msvcp140d.dll) in networktest.exe: 0xC0000005: Access violation reading location 0x00000000.
`

Is there any solution for this?

**Comment by embeddedmz** [comment]
Can you post the code snippet showing the use of the class ?

0x00000000 => apparently you are trying to access a null pointer.

**Comment by revson1** [comment]
it isn't my code, its code provided in socket.cpp

**Comment by embeddedmz** [comment]
I can't help you if you don't show me your Visual Studio solution. Maybe your VS project isn't correctly configured :  for example, did you forget to add the .cpp files to your VS project ?

Otherwise, you can follow the "read me" file and use CMake to generate a VS solution to build the class in a static library.
