### ISSUE TITLE
Configuration incomplete, errors occured

### ISSUE THREAD

**Issue by valtsu41** [embeddedmz/socket-cpp#9]
This is what happens when I try to cmake a release static library:

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.7/Modules/FindGTest.cmake:194 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  SocketTest/CMakeLists.txt:16 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/C++ sockets/socket-cpp-master/build/CMakeFiles/CMakeOutput.log".

I am using raspbian stretch on raspberry pi 3 model b

**Comment by valtsu41** [comment]
Here is the CMakeOutput.log
[CMakeOutput.log](https://github.com/embeddedmz/socket-cpp/files/2634418/CMakeOutput.log)

**Comment by 408b7f8b** [comment]
Do you have OpenSSL and Google Test installed?

**Comment by valtsu41** [comment]
Ok, it seems like I have somehow managed to skip the Google Test part. I checked OpenSSL but not that. I'll try to install it. (I'll close this if it works...)

**Comment by embeddedmz** [comment]
In the root CMakeLists.txt, you can comment "add_definitions(-DOPENSSL)" if you don't need secure TCP classes, and rebuild the library. (In the future, this can be set when calling cmake...)

If you don't want to run unit tests (so you don't need Google Test), you can comment the lines between 17 (add_subdirectory(SocketTest)) and the end of the root CMakeLists file to avoid generating a test binary.

To comment a line in a CMake file, use the # character.

If you don't have OpenSSL, you can google "openssl raspberry" the first result will help you to install the latest version of it. (for Google Test : https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/ it works also for your platform)

Regards.

**Comment by valtsu41** [comment]
Now this error happens after "make" (not the whole log)

.cpp:9:0:
/home/pi/C++ sockets/socket-cpp-master/Socket/SecureSocket.h:14:25: fatal error: openssl/bio.h: Tiedostoa tai hakemistoa ei ole
 #include <openssl/bio.h>
                         ^

Translation: There is no file or directory.

**Comment by valtsu41** [comment]
And i **should** have openssl

**Comment by embeddedmz** [comment]
I recommend you to have an installation of the most recent version of OpenSSL along with the old version that you can have on your platform : Download https://www.openssl.org/source/openssl-1.1.1a.tar.gz and you can use this tutorial https://blacksaildivision.com/how-to-install-openssl-on-centos to help you install OpenSSL under /usr/local

Recently, I tried to hint cmake of the directories of a recent version of OpenSSL that I have installed on Centos 7 and it didn't work (cmake -DOPENSSL_INCLUDE_DIR=/usr/local/openssl/include -DOPENSSL_LIBRARIES=/usr/local/openssl/lib -DCMAKE_BUILD_TYPE=Debug)
 
I have to comment those lines on the CMakeLists files

#include_directories(${OPENSSL_INCLUDE_DIR})
#link_directories(${OPENSSL_LIBRARIES})

and replace them with the direct path :

include_directories(/usr/local/openssl/include)
link_directories(/usr/local/openssl/lib)

**Comment by valtsu41** [comment]
Great, it seems like I do not have any of those lines.

**Comment by embeddedmz** [comment]
Nope !

**Comment by valtsu41** [comment]
Yes! I finally managed to do this! I found out I had openssl but no libssl, so I installed it and started to detect it. Thank you for help!
